---
language: go
go:
  - "1.9.x"
  - "1.10.x"
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - make dependencies
script: make test
before_deploy:
  - ./scripts/compile.sh ${TRAVIS_TAG}
deploy:
  - provider: releases
    api_key:
      secure: M92ekUkZ5Z6x8szhl/xOg/SsZesfc9osI8HXIPMHERehDZxyWyKHuzWFXhjDyuTDER6EYibqG9KJbEBXKlUaBfKPqZSj4G/PZVjoSFStanJbF47AGw4K+j5xDRTTVzvW7vPXqPTz7urllD1Ov7iCs9iO9d5XWtJNyKEXfRyeohfnUqG9rBZk+bVXMYf3Tr1W3LL1VGnBIKbyQ6v09xAFKJtwUM7Ah7kzcO0nDw6oUJEIbEtPQi0oMIC0p+uFqavf/Q7SsSOQOpiIBn57wABm3mk7z+w5Cct2u3+8Bz43KKLsBj6u1wlPeTgtYEhxnvsYYMgKTawdOogdXpHLfaKDeSJOXYEJb/pGiozIB/zGz0GGbzcFQ07o6jOTkzUHWDHhKKoovpu5cty7CibYwB/of6EjD2bfERu8Ua2OSLYBNc8nPjBJ6CMfPsYTY1wWbSC2uP19qY3rIUg6Sf03FP6D5MFQ9cNeM5mT/Ic7XzjkSrx4DJE59/H5Ss76mYfgsIy2ER3lMHeh1vXXlW5B0fa1ZR4t96VdyFzjoPiPkOh1MbU0OTmRgMPqXlA3IdUXu0H2nywxuULGRZgPF1nmMXsmzcQhYtn/mF8mx9bQzC7rIdsK7j3Q/YBK+GKFeAGIHnLgJL82Mr6vXoT9mbSXS9ShkaFJSGu7Wy7BigENr9NBgko=
    skip_cleanup: true
    file_glob: true
    file: binaries/*
    name: Version ${TRAVIS_TAG}
    prerelease: false
    on:
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
      repo: itskingori/sanaa
      tags: true
  - provider: releases
    api_key:
      secure: M92ekUkZ5Z6x8szhl/xOg/SsZesfc9osI8HXIPMHERehDZxyWyKHuzWFXhjDyuTDER6EYibqG9KJbEBXKlUaBfKPqZSj4G/PZVjoSFStanJbF47AGw4K+j5xDRTTVzvW7vPXqPTz7urllD1Ov7iCs9iO9d5XWtJNyKEXfRyeohfnUqG9rBZk+bVXMYf3Tr1W3LL1VGnBIKbyQ6v09xAFKJtwUM7Ah7kzcO0nDw6oUJEIbEtPQi0oMIC0p+uFqavf/Q7SsSOQOpiIBn57wABm3mk7z+w5Cct2u3+8Bz43KKLsBj6u1wlPeTgtYEhxnvsYYMgKTawdOogdXpHLfaKDeSJOXYEJb/pGiozIB/zGz0GGbzcFQ07o6jOTkzUHWDHhKKoovpu5cty7CibYwB/of6EjD2bfERu8Ua2OSLYBNc8nPjBJ6CMfPsYTY1wWbSC2uP19qY3rIUg6Sf03FP6D5MFQ9cNeM5mT/Ic7XzjkSrx4DJE59/H5Ss76mYfgsIy2ER3lMHeh1vXXlW5B0fa1ZR4t96VdyFzjoPiPkOh1MbU0OTmRgMPqXlA3IdUXu0H2nywxuULGRZgPF1nmMXsmzcQhYtn/mF8mx9bQzC7rIdsK7j3Q/YBK+GKFeAGIHnLgJL82Mr6vXoT9mbSXS9ShkaFJSGu7Wy7BigENr9NBgko=
    skip_cleanup: true
    file_glob: true
    file: binaries/*
    name: Version ${TRAVIS_TAG}
    prerelease: true
    on:
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.+$
      repo: itskingori/sanaa
      tags: true
after_deploy:
  - "./scripts/trigger.sh ${TRAVIS_TAG}"
env:
  global:
    - secure: QU8cQO//Q15fPApmjmO47OZ6l84KqcFj9V6flGerOEVXvZoPhspE2JbLyit2lhlIsgcC0ljHWviXvjH3DxRmSnlZo9/PlIC+aAQ+g4cqOIgY+o4uEA/opRiXqHIv+ctPvdg5JlRuF8RxFgNX8iRR2lu52btwby4G/oaqI3Dm+G5/NVR3cuIjXc18MciPP50oyiMlScTP28pYKFM+oPxDGrCVOC/Lmwhf3qMGMD+TsdlYtlgMA+gbN/dtZHwqpplhq9yKFdWVF202OnpsFdedOZrjd7NTayiOdYAnwc6DC2JtJk9k3IMfS4uFSAnfhYnVLPoHWNMEfJIKWJR934LQ0ieckEhOJQoW5DeXJ/a9qG8wVtur0PShyNj/Z9v8mj7KTHiGF0gxaW0m5nmrYIT5mZHE97c1Sh3fHt31Fv+tCjaYorCrF4uvNpLff1AfDoy9ZMJJDm/NYX6e5Oc7JIPd/9/eW4oIJn5jmd6Xue6Rs/+O+jrB2KcQOCRIterKSD/JpusrUSS5M+yQVA+/roxEyiOVd0RknWIp8GLIzcWQd5rZM1MoChRstBMzB33Xft3B7q0ufvnsVeReOOtPMHtBk0TJC3yTUNmOtEOnMjf1l2KCSYTvex85jmkhISOrVRn1xfRbGHZPNK2US+EkaxTHii1evfg9YT5DR1T3hmACMP8=
