---
language: go
go:
  - 1.9.x
before_install:
  - curl "https://glide.sh/get" | sh
  - make install
script: make test
before_deploy:
  - ./scripts/compile.sh ${TRAVIS_TAG}
deploy:
  - provider: releases
    api_key:
      secure: M92ekUkZ5Z6x8szhl/xOg/SsZesfc9osI8HXIPMHERehDZxyWyKHuzWFXhjDyuTDER6EYibqG9KJbEBXKlUaBfKPqZSj4G/PZVjoSFStanJbF47AGw4K+j5xDRTTVzvW7vPXqPTz7urllD1Ov7iCs9iO9d5XWtJNyKEXfRyeohfnUqG9rBZk+bVXMYf3Tr1W3LL1VGnBIKbyQ6v09xAFKJtwUM7Ah7kzcO0nDw6oUJEIbEtPQi0oMIC0p+uFqavf/Q7SsSOQOpiIBn57wABm3mk7z+w5Cct2u3+8Bz43KKLsBj6u1wlPeTgtYEhxnvsYYMgKTawdOogdXpHLfaKDeSJOXYEJb/pGiozIB/zGz0GGbzcFQ07o6jOTkzUHWDHhKKoovpu5cty7CibYwB/of6EjD2bfERu8Ua2OSLYBNc8nPjBJ6CMfPsYTY1wWbSC2uP19qY3rIUg6Sf03FP6D5MFQ9cNeM5mT/Ic7XzjkSrx4DJE59/H5Ss76mYfgsIy2ER3lMHeh1vXXlW5B0fa1ZR4t96VdyFzjoPiPkOh1MbU0OTmRgMPqXlA3IdUXu0H2nywxuULGRZgPF1nmMXsmzcQhYtn/mF8mx9bQzC7rIdsK7j3Q/YBK+GKFeAGIHnLgJL82Mr6vXoT9mbSXS9ShkaFJSGu7Wy7BigENr9NBgko=
    skip_cleanup: true
    file_glob: true
    file: binaries/*
    on:
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
      prerelease: false
      repo: itskingori/sanaa
      tags: true
