[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.30"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gocraft/work"
  version = "0.5.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/itskingori/go-wkhtml"
  version = "1.0.0-rc1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[prune]
  go-tests = true
  unused-packages = true
