source "https://rubygems.org"

ruby '2.4.2'

# Bootstrap the GitHub Pages Jekyll environment locally.
gem "github-pages"

# Test your rendered HTML files to make sure they're accurate.
gem 'html-proofer'

# Rake is a Make-like program implemented in Ruby.
gem 'rake'
