---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sanaa-worker
  namespace: default
  labels:
    app: sanaa
    role: worker
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: sanaa-worker
  namespace: default
  labels:
    app: sanaa
    role: worker
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sanaa
      role: worker
  template:
    metadata:
      labels:
        app: sanaa
        role: worker
    spec:
      serviceAccountName: sanaa-worker
      containers:
        - name: worker
          image: kingori/sanaa:0.5.0
          args:
            - worker
            - --concurrency=10
            - --redis-host=sanaa-redis.default.svc.cluster.local
            - --s3-bucket=sanaa-output-bucket
            - --s3-region=us-east-1
            - --verbose
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "some-key"
            - name: AWS_SECRET_ACCESS_KEY
              value: "some-secret"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 256Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
